version: "3"
services:
  db:
    image: postgres
    ports:
      - "8787:8787"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "db"
    restart: unless-stopped
  node-app:
    build: .
    ports:
      - "8888:8888"
    restart: unless-stopped
